import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ScanData {
  projectName: string;
  domain: string;
  scanDate: string;
  overallScore: number;
  results: Array<{
    provider: string;
    queryText: string;
    aiResponseRaw: string;
    metrics: {
      is_visible: boolean;
      sentiment_score: number;
      citation_found: boolean;
      ranking_position: number | null;
      recommendation_strength: number;
    } | null;
  }>;
}

interface Averages {
  visibilityRate: number;
  avgSentiment: number;
  citationRate: number;
  avgRecommendation: number;
}

export function exportScanToPDF(scanData: ScanData, averages: Averages): void {
  const doc = new jsPDF();
  let yPos = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('GEO Analysis Report', 20, yPos);
  
  yPos += 15;

  // Project Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Project: ${scanData.projectName}`, 20, yPos);
  yPos += 7;
  doc.text(`Domain: ${scanData.domain}`, 20, yPos);
  yPos += 7;
  doc.text(`Scan Date: ${scanData.scanDate}`, 20, yPos);
  
  yPos += 15;

  // Overall Metrics Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Performance', 20, yPos);
  yPos += 10;

  // Metrics Table
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Score']],
    body: [
      ['Overall Score', `${scanData.overallScore}/100`],
      ['Visibility Rate', `${averages.visibilityRate.toFixed(1)}%`],
      ['Average Sentiment', getSentimentLabel(averages.avgSentiment)],
      ['Citation Rate', `${averages.citationRate.toFixed(1)}%`],
      ['Avg Recommendation', `${averages.avgRecommendation.toFixed(0)}/100`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] }, // Blue
    margin: { left: 20 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Provider Performance Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  
  // Check if we need a new page
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  doc.text('Provider Performance', 20, yPos);
  yPos += 10;

  // Calculate provider stats
  const providerStats = calculateProviderStats(scanData.results);
  const providerTableData = Object.entries(providerStats).map(([provider, stats]) => [
    provider,
    `${stats.visibilityRate.toFixed(0)}%`,
    getSentimentLabel(stats.avgSentiment),
    `${stats.citationRate.toFixed(0)}%`,
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [['Provider', 'Visibility', 'Sentiment', 'Citation']],
    body: providerTableData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: 20 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Detailed Results Section
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Results', 20, yPos);
  yPos += 10;

  // Results for each query
  scanData.results.forEach((result, index) => {
    // Check if we need a new page
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${result.provider}`, 20, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    // Query
    const queryLines = doc.splitTextToSize(`Query: ${result.queryText}`, 170);
    doc.text(queryLines, 20, yPos);
    yPos += queryLines.length * 5 + 3;

    // Metrics
    if (result.metrics) {
      const metricsText = [
        `Visible: ${result.metrics.is_visible ? 'Yes' : 'No'}`,
        `Sentiment: ${getSentimentLabel(result.metrics.sentiment_score)}`,
        `Citation: ${result.metrics.citation_found ? 'Yes' : 'No'}`,
        `Recommendation: ${result.metrics.recommendation_strength}/100`,
      ].join(' | ');
      
      doc.setFont('helvetica', 'italic');
      doc.text(metricsText, 20, yPos);
      yPos += 7;
    }

    // Response (truncated)
    doc.setFont('helvetica', 'normal');
    const responsePreview = result.aiResponseRaw.substring(0, 200) + '...';
    const responseLines = doc.splitTextToSize(responsePreview, 170);
    doc.text(responseLines, 20, yPos);
    yPos += responseLines.length * 5 + 10;
  });

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by GEO Analyser - Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const filename = `GEO_Report_${scanData.projectName.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  doc.save(filename);
}

function getSentimentLabel(score: number): string {
  if (score > 0.3) return 'Positive';
  if (score < -0.3) return 'Negative';
  return 'Neutral';
}

function calculateProviderStats(
  results: ScanData['results']
): Record<string, { visibilityRate: number; avgSentiment: number; citationRate: number }> {
  const stats: Record<string, any> = {};

  results.forEach((result) => {
    if (!stats[result.provider]) {
      stats[result.provider] = {
        visible: 0,
        sentimentSum: 0,
        citations: 0,
        total: 0,
      };
    }

    if (result.metrics) {
      stats[result.provider].total++;
      if (result.metrics.is_visible) stats[result.provider].visible++;
      if (result.metrics.citation_found) stats[result.provider].citations++;
      stats[result.provider].sentimentSum += result.metrics.sentiment_score;
    }
  });

  // Calculate percentages and averages
  Object.keys(stats).forEach((provider) => {
    const s = stats[provider];
    stats[provider] = {
      visibilityRate: s.total > 0 ? (s.visible / s.total) * 100 : 0,
      avgSentiment: s.total > 0 ? s.sentimentSum / s.total : 0,
      citationRate: s.total > 0 ? (s.citations / s.total) * 100 : 0,
    };
  });

  return stats;
}
